logging:
  level:
    studio.lab9.socks: DEBUG # Capture all BinanceService and config logs

spring:
  main:
    banner-mode: "off"
  task:
    execution:
      pool:
        max-size: 20 # Handle WebSocket load
server:
  port: 8000
  tomcat:
    threads:
      max: 100 # Support client connections