name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build builder Docker image
        run: |
          if ! docker image ls -q socks-builder | grep -q .; then
            cd $GITHUB_WORKSPACE
            docker build -f docker/builder.dockerfile -t socks-builder docker
          fi

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE && docker build -t socks .          

      - name: Restart Docker Compose service
        run: |
          cd /home/ubuntu
          docker compose down socks && docker compose up -d socks          

      - name: Copy checked out code to NGINX projects directory
        run: |
          rm -rf /home/ubuntu/nginx/dev/socks/*
          cp -r $GITHUB_WORKSPACE/* /home/ubuntu/nginx/dev/socks/
